sudo: required
services:
  - docker

before_install:
  - docker build -t 19872019/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 19872019/react-test npm test -- --coverage

after_success:
  - docker build -t 19872019/multi-client ./client
  - docker build -t 19872019/multi-nginx ./nginx
  - docker build -t 19872019/multi-server ./server
  - docker build -t 19872019/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 19872019/multi-client
  - docker push 19872019/multi-nginx
  - docker push 19872019/multi-server
  - docker push 19872019/multi-worker


  deploy:
      provider: elasticbeanstalk
      region: us-west-2
      app: multi
      env: Multi-env
      bucket_name: elasticbeanstalk-us-west-2-979026322802
      bucket_path: docker-multi
      on:
          branch: master
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key:
          secure: $AWS_SECRET_KEY